# Generated by Django 3.0 on 2020-06-03 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0002_auto_20200603_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
