# Generated by Django 3.0 on 2020-06-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0003_files_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
