# Generated by Django 3.0 on 2020-06-10 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0004_auto_20200603_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='files',
            name='result',
            field=models.CharField(default='', max_length=500),
        ),
    ]
